#pragma once

#include<string>

class int3;

enum TreasureType {

    BUILDING_TIER_TAB,

    BUILDING_ARENA,
    BUILDING_FEARIE_RING_DIRT,
    BUILDING_FOUNTAIN_OF_FORTUNE,
    BUILDING_FOUNTAIN_OF_YOUTH,
    BUILDING_IDOL_OF_FORTUNE,
    BUILDING_LEARNING_STONE,
    BUILDING_LIBRARY_OF_ENLIGHTENMENT,
    BUILDING_MARLETTO_TOWER,
    BUILDING_MERCENARY_CAMP,
    BUILDING_OASIS,
    BUILDING_RALLY_FLAG,
    BUILDING_SCHOOL_OF_MAGIC,

    LOW_TIER_TAB,

    RESOURCE_WOOD,
    RESOURCE_SULFUR,
    RESOURCE_CRYSTAL,
    RESOURCE_GEMS,
    RESOURCE_ORE,
    RESOURCE_MERCURY,
    RESOURCE_GOLD, 

    MID_TIER_TAB,

    ARTIFACT_LADYBIRD_OF_LUCK,
    ARTIFACT_STATESMANS_MEDAL,
    ARTIFACT_CLOVER_OF_FORTUNE,
    ARTIFACT_EMBLEM_OF_COGNIZANCE,
    ARTIFACT_RING_OF_VITALITY,
    ARTIFACT_TALISMAN_OF_MANA,
    ARTIFACT_SPYGLASS,
    ARTIFACT_STOIC_WATCHMAN,
    ARTIFACT_SPECULUM,
    ARTIFACT_CHARM_OF_MANA,
    ARTIFACT_RING_OF_LIFE,
    ARTIFACT_BADGE_OF_COURAGE,
    ARTIFACT_SHIELD_OF_THE_DWARVEN_LORDS,
    ARTIFACT_BUCKLER_OF_THE_GNOLL_KING,
    ARTIFACT_GREATER_GNOLLS_FLAIL,
    ARTIFACT_DRAGON_WING_TABARD,


    HIGH_TIER_TAB,

    ARTIFACT_RING_OF_THE_WAYFARER,
    ARTIFACT_RING_OF_INFINITE_GEMS,
    ARTIFACT_EQUESTRIANS_GLOVES,
    ARTIFACT_SANDALS_OF_THE_SAINT,
    ARTIFACT_PENDANT_OF_LIFE,
    ARTIFACT_PENDANT_OF_COURAGE,
    ARTIFACT_PENDANT_OF_FREE_WILL,
    ARTIFACT_PENDANT_OF_HOLINESS,
    ARTIFACT_PENDANT_OF_TOTAL_RECALL,
    ARTIFACT_CAPE_OF_CONJURING,
    ARTIFACT_BOWSTRING_OF_THE_UNICORNS_MANE,
    ARTIFACT_BOOTS_OF_POLARITY,
    ARTIFACT_NECKLACE_OF_SWIFTNESS,
    ARTIFACT_VIAL_OF_LIFEBLOOD,
    ARTIFACT_NECKLACE_OF_OCEAN_GUIDANCE,
    ARTIFACT_BREASTPLATE_OF_PETRIFIED_WOOD,
    ARTIFACT_SURCOAT_OF_COUNTERPOISE,
    ARTIFACT_HELM_OF_THE_ALABASTER_UNICORN,
    ARTIFACT_ARMOR_OF_WONDER,
    ARTIFACT_GLYPH_OF_GALLANTRY,
    ARTIFACT_SENTINELS_SHIELD,
    ARTIFACT_DRAGON_SCALE_SHIELD,
    ARTIFACT_ANGEL_FEATHER_ARROWS,

    
    END_TIER_TAB


};


std::string treasureTypeToString(TreasureType treasureType);

TreasureType stringtoTreasureType(std::string treasureType);

int3 getTreasureSize(TreasureType treasureType);